#+TITLE: Project Scratch

* Tram tracker
https://github.com/pizza1016/ptv-timetable/blob/trunk/tramtracker/asyncapi.py#L76
Using aiohttp.client ClientSession
- This uses async, and an event loop must be running (I don't know what this means...)
* Requirements
- =openmeteo-requests=
- =pyserial=
- =pandas=
- =requests-cache=
- =retry-requests=
- =aiohttp=
* How to develop
Push and pull from the Raspberry Pi as needed. If you run into credentials trouble, run:
#+begin_src sh
bash ~/load_github_credentials.sh
#+end_src

* Automatically starting with systemd
In order to run on boot, I created a Systemd Service, located at =/lib/systemd/system/rpi-lcd.service=.
#+begin_src sh
[Unit]
Description=Run the python program to control the Arduino keypad and LCD screen
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=kitchenpi
WorkingDirectory=/home/<USERNAME>/Documents/RPi_LCD
ExecStart=/home/<USERNAME>/Documents/RPi_LCD/env/bin/python main.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
#+end_src

Then, reload systemd, enable on boot, and start it now!
#+begin_src sh
sudo systemctl daemon-reload
sudo systemctl enable rpi-lcd.service
sudo systemctl start rpi-lcd.service
#+end_src

* TODOs
** Manual
*** General
- [ ] Set the python [[* Python testing][interpreter path]] in the python testing section correctly!
- [ ] Use async for button presses
- [ ] Create settings app to control
  - Brightness
  - Hostname?
** Scanner
Run scanner by moving cursor inside codeblock, then executing code =C-c C-c=
#+NAME: scan-todos
#+BEGIN_SRC emacs-lisp :results none
(require 'cl-lib)
(let* ((root (file-name-directory (buffer-file-name)))
       (default-directory root)
       (raw (shell-command-to-string
             "git grep -n 'TODO:' -- ':!./logs/*' ':!*.pt' ':!*.npz' ':!*.npy' ':!*.pkl'"))
       (output ""))
  (dolist (line (split-string raw "\n" t))
    (when (string-match "^\\([^:]+\\):\\([0-9]+\\):.*TODO:[[:space:]]*\\(.*\\)$" line)
      (let* ((rel  (match-string 1 line))
             (lnum (string-to-number (match-string 2 line)))
             (text (string-trim (match-string 3 line)))
             (header (format "*** ~%s~\n" rel)))
        (unless (string-match-p (regexp-quote header) output)
          (setq output (concat output header)))
        (setq output (concat output
                             (format "    - Line %d: %s [[file:%s::%d][→]]\n"
                                     lnum text rel lnum))))))
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward "^\\*\\* Items$" nil t)
      (forward-line 1)
      (let ((start (point))
            (end (save-excursion
                   (if (re-search-forward "^\\* " nil t)
                       (line-beginning-position)
                     (point-max)))))
        (delete-region start end)
        (insert "\n" (if (string-empty-p output) "   /No TODOs found./\n" output) "\n")))))
#+END_SRC

** Items

   /No TODOs found./

* Python testing
#+begin_src emacs-lisp
(setq org-babel-python-command "/path/to/env/bin/python3")
#+end_src

#+RESULTS:
: /path/to/env/bin/python3

* Keybinds
** Navigation
*** ] ] - org-next-visible-heading
Next heading
*** [ [ - org-previous-visible-heading
Previous heading
*** ] h - org-forward-heading-same-level
Next heading same level
*** [ h - org-backward-heading-same-level
Previous heading same level
*** z u - outline-up-heading
Backward to higher level heading
*** C-c C-j - org-goto
Jump to different place without changing the current outline visibility
** Visualising
*** z c - +org/close-fold
Folds current heading
*** z M - +org/close-all-folds
Folds all visual headings
** Correcting
*** ] s - +spell/next-error
Next ispell error
*** [ s - +spell/previous-error
Previous ispell error
** Toggling
*** SPC m x - org-toggle-checkbox
Toggle checkbox, from [ ] to [X]
*** SPC u SPC u SPC m x - [double prefix] org-toggle-checkbox
Set checkbox to "[-]"
** Selecting and surrounding
*** v i &optional - evil-inner-paren
Select inner parenthesis, &optional can be (, ", [ etc.
*** S &optional - evil-surround-region
Surround selected region with the &optional chars

* Searcher
Change ~search_string~ value to search for a particular string.
        e.g. ~search_string="flowpose"~
Change ~excluded_dirs~ to exclude particular directories from grep search.
        e.g. ~excluded_dirs=(":!./logs/*" ":!./env/*")~
#+begin_src bash :results output
## ----------------------
search_string="grey"
excluded_dirs=(":!./logs/*" ":!./env/*")
## ----------------------

# Search for the file names
git grep -l $search_string -- ${excluded_dirs[@]}
# Provide a file count
echo -e "\nThere are $(git grep -l $search_string -- ${excluded_dirs[@]} | wc -l) files containing '${search_string}'"
#+end_src

#+RESULTS:
: demo.py
: utils.py
:
: There are 2 files containing 'grey'

